# Generated by Django 4.2.11 on 2025-06-26 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_popular', models.BooleanField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Facility', 'Facility')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
            },
        ),
        migrations.CreateModel(
            name='PlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('feature', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membershipplan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
            },
        ),
    ]
