# Generated by Django 4.2.11 on 2025-06-26 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fac_title', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('fac_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('fac_city', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_state', models.IntegerField(blank=True, null=True)),
                ('fac_cntry', models.IntegerField(blank=True, null=True)),
                ('fac_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_contact_num', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_ein_number', models.IntegerField(blank=True, null=True)),
                ('fac_wrk_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_weekly_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_npi', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_e_sign', models.FileField(blank=True, null=True, upload_to='uploads/facility/e-sign')),
                ('fac_activated_on', models.DateTimeField(blank=True, null=True)),
                ('fac_status', models.CharField(blank=True, choices=[('Waiting for Confirmation', 'Waiting for Confirmation'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=100, null=True)),
                ('fac_logo', models.FileField(blank=True, null=True, upload_to='uploads/facility/logo')),
                ('fac_discipline', models.ManyToManyField(to='modules.discipline')),
                ('fac_doc_soft', models.ManyToManyField(to='modules.docsoftware')),
                ('fac_langs', models.ManyToManyField(to='modules.languages')),
                ('fac_speciality', models.ManyToManyField(to='modules.speciality')),
                ('fac_wrk_setting', models.ManyToManyField(to='modules.worksettingexp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='VisitSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('facility_id', models.IntegerField(blank=True, default=0, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('dates', models.JSONField(blank=True, default=dict, null=True)),
                ('result_count', models.IntegerField(blank=True, default=0, null=True)),
                ('professional_ids', models.JSONField(blank=True, default=dict, null=True)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('license', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100, null=True)),
                ('cpr_bls', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100, null=True)),
                ('discipline', models.ManyToManyField(to='modules.discipline')),
                ('job_type', models.ManyToManyField(to='modules.jobtype')),
                ('languages', models.ManyToManyField(to='modules.languages')),
                ('speciality', models.ManyToManyField(to='modules.speciality')),
                ('visit_type', models.ManyToManyField(to='modules.visittype')),
                ('work_setting', models.ManyToManyField(to='modules.worksetting')),
            ],
            options={
                'verbose_name': 'Visit search',
                'verbose_name_plural': 'Visit searches',
            },
        ),
        migrations.CreateModel(
            name='FacilityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('years_of_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('cpr_bls', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3, null=True)),
                ('license', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100, null=True)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.discipline')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.jobtype')),
                ('languages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.languages')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.speciality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.visittype')),
                ('work_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.worksetting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityDocSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('setting_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_expired', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('discipline', models.ManyToManyField(to='modules.discipline')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
            ],
            options={
                'verbose_name': 'Facility DocSetting',
                'verbose_name_plural': 'Facility DocSettings',
            },
        ),
    ]
