# Generated by Django 4.2.11 on 2025-06-26 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfessionalRequestMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message_from', models.IntegerField(blank=True, null=True)),
                ('message_to', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Open', 'Open'), ('Deleted', 'Deleted')], max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_request.jobprofessionalrequest')),
            ],
            options={
                'verbose_name': 'Job Professional Request Message',
                'verbose_name_plural': 'Job Professional Request Messages',
            },
        ),
    ]
