# Generated by Django 4.2.11 on 2025-06-26 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        ('job_request', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('contract_no', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New')], default='New', max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_request.jobprofessionalrequest')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractWorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled')], default='Active', max_length=100, null=True)),
                ('cancel_user_type', models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Facility', 'Facility'), ('None', 'None')], default='None', max_length=100, null=True)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('job_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobhours')),
                ('professional_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.professionalhours')),
            ],
            options={
                'verbose_name': 'Contract Work Hour',
                'verbose_name_plural': 'Contract Work Hours',
            },
        ),
        migrations.CreateModel(
            name='ContractHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Active', max_length=100, null=True)),
                ('cancel_user_type', models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Facility', 'Facility'), ('None', 'None')], default='None', max_length=100, null=True)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('job_work_hours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobworkhours')),
                ('professional_slots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.professionalslots')),
            ],
            options={
                'verbose_name': 'Contract Hour',
                'verbose_name_plural': 'Contract Hours',
            },
        ),
    ]
