# Generated by Django 4.2.11 on 2025-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracthours',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Invoiced', 'Invoiced')], default='Active', max_length=100, null=True),
        ),
    ]
