# Generated by Django 4.2.11 on 2025-06-26 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityGroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fac_id', models.IntegerField(blank=True, null=True)),
                ('fac_grp_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Facility Group Link',
                'verbose_name_plural': 'Facility Group Links',
            },
        ),
        migrations.CreateModel(
            name='FacilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fac_grp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fac_grp_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_grp_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_grp_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_grp_address', models.CharField(blank=True, max_length=255, null=True)),
                ('fac_grp_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('fac_grp_city', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_grp_state', models.IntegerField(blank=True, null=True)),
                ('fac_grp_cntry', models.IntegerField(blank=True, null=True)),
                ('fac_grp_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('fac_grp_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility Group',
                'verbose_name_plural': 'Facility Groups',
            },
        ),
    ]
