# Generated by Django 4.2.11 on 2025-06-26 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfessionalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('Open', 'Open'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('In Process', 'In Process'), ('Rejected', 'Rejected'), ('Confirmed', 'Confirmed'), ('Deleted', 'Deleted'), ('Contract Created', 'Contract Created')], default='New', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.professional')),
            ],
            options={
                'verbose_name': 'Job Professional Request',
                'verbose_name_plural': 'Job Professional Requests',
            },
        ),
    ]
